[build]
  functions = "src"  # indique où se trouvent les fonctions Netlify (dans le dossier 'api')

[build.environment]
  PYTHON_VERSION = "3.9"  # Assure-toi que tu choisis une version compatible avec ton code

[context.production.environment]
  # Variables d'environnement pour ton environnement de production (par exemple, clés API)
  MY_ENV_VARIABLE = "value"
